# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 036d548c03f23496169ee6629c58eed83239d1f858012c30b4e5bd56fcefdee677e58c1268f147169b16883d0d5073356f4811ccd3b59a9d4d2b4d7069b6645a

test:
  secret_key_base: c2e383c348cd3fbe274b8d0bead04362c3a676d66da872f3480f9a755b21d8820807337469d56f1a856fda9b43416b0576697dea08ac8dec20ddc747a4b7758f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
